# Generated by Django 4.0 on 2022-01-03 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0004_alter_appoint_idpkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='idpkid',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
