# Generated by Django 4.0 on 2022-01-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appointments', '0006_remove_appoint_idpkid_appoint_idpkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='idpkid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
