# Generated by Django 3.2.9 on 2021-12-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nameqaz',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='titleqaz',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
