# Generated by Django 3.2.9 on 2021-12-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20211210_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
