# Generated by Django 4.0 on 2022-01-09 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_alter_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='John', on_delete=django.db.models.deletion.CASCADE, to='newapp.author', verbose_name='Автор (author)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Nature', null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.category', verbose_name='Категория(category)'),
        ),
    ]
